### ISSUE TITLE
Make OS package dependencies part of ocrd-tool.json

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#131]
If `ocrd-tool.json` contained a list of system packages required, we'd had a uniform way to express system depencies, the `make deps-ubuntu` target would be redundant and we could generate documentation from it.

E.g. for `ocrd_tesserocr`:

```yaml
 {
   "version": "0.6.0",
   "git_url": "https://github.com/OCR-D/ocrd_tesserocr",
   "dockerhub": "ocrd/tesserocr",
   "os_deps": {
     "ubuntu_18_04": ["git", "python3", "python3-pip", "libtesseract-dev", "libleptonica-dev", "tesseract-ocr-eng", "tesseract-ocr"]
   },
  # [..]
```

Can be queried, e.g. with jq:

```sh
sudo apt-get install -y $(jq -r '.os_deps.ubuntu_18_04[]' ~monorepo/ocrd_tesserocr/ocrd-tool.json)
```

We could get a list of all system packages by analyzing all the ocrd-tool.json files in our monorepo or stweil/ocrd_all to install required packages in one go.

What do you think?
