### ISSUE TITLE
Required parameter 'level-of-operation'

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#134]
Since this is a setting that concerns most if not all processors, it would IMHO make sense to require processors to implement a parameter `level-of-operation` the way [tesserocr does](https://github.com/OCR-D/ocrd_tesserocr/blob/master/ocrd_tesserocr/ocrd-tool.json#L48-L53).

The possible values would be `page`, `region`, `line`, `word` and `glyph`.

Prrocessors may restrict this further with an enum in the definition for the levels they support and can override the default.

What do you think? @bertsky @wrznr @mjenckel @khurramHashmi

**Comment by bertsky** [comment]
I am much in favour of a uniform parameter name for this in the spec. 

I would even argue that usually processors should provide that parameter (with a default) even in the case where they only allow one specific value/level, so users can quickly assess where they can place them in the workflow – except of course if this is already unambiguous by the name (e.g. `segment-region`) or definition of the operation (e.g. cropping, image characterization)

However, we must be careful with the wording. Currently, we've got:
- `textequiv_level` in
  * `ocrd-tesserocr-recognize` `ocrd-cis-ocropy-recognize` (for the lowest **output** level – input level is then:
     - region, if output level is `region`
     - line, otherwise)
  * `ocrd-keraslm-rate` `ocrd-cor-asv-ann-process` (for **both** input and output level)
    
  This usually affects the levels above that, too!
- `operation_level` in
  * `ocrd-tesserocr-deskew` `ocrd-tesserocr-binarize` `ocrd-anybaseocr-deskew` `ocrd-anybaseocr-dewarp` (with the usual semantics)
  * `ocrd-anybaseocr-block-segmentation` `ocrd-anybaseocr-tiseg` `ocrd-anybaseocr-textline` (still unclear)
- `level-of-operation` in
  * `ocrd-cis-ocropy-binarize` `ocrd-cis-ocropy-denoise` `ocrd-cis-ocropy-deskew` `ocrd-cis-ocropy-clip` `ocrd-kraken-binarize` `ocrd-anybaseocr-binarize` (with the usual semantics)
  * `ocrd-cis-ocropy-segment` (for the **input** level – output level will be 1 lower)

Candidates where that parameter should probably be added, even though they are fixed to 1 level:
- `ocrd-im6convert` (page)
- `ocrd-olena-binarize` (page)
- `ocrd-typegroups-classifier` (page)
- `ocrd-segment-repair` (region)
- `ocrd-cis-ocropy-resegment` (line)
- `ocrd-cis-ocropy-dewarp` (line)
- `ocrd-calamari-recognize` (line)
- `ocrd-cor-asv-ann-evaluate` (line)
- `ocrd-dinglehopper` (line)

Candidates where that parameter could be used to unify multiple processors into one:
- `ocrd-tesserocr-segment-*`
- `ocrd-segment-extract-*`

**Comment by wrznr** [comment]
It would be great if we could make this consistent over all processors. I.e. move the level of application from the processor's name into a parameter (`tesserocr` and `segment`) and choose a uniform name for the parameter. I guess that the quick assessment of the level of operation for processors which are not variable in this respect could also be achieved by proper documentation and sample workflows.

**Comment by kba** [comment]
According to our [glossary](https://ocr-d.github.io/glossary), `region` should be `block`.

 How about two parameters `input-level` (IL) and `output-level` (OL)?

 ```yaml
 # Processor must ensure that IL and OL are compatible. Might be accomplished with JSON-Schema hack
 ocrd-tesserocr-recognize, ocrd-cis-ocropy-recognize, ocrd-ocropy-recognize:
 | IL:
     - block
     - line
 | OL:
     - block
     - line

 ocrd-tesserocr-deskew,, ocrd-tesserocr-binarize,, ocrd-anybaseocr-deskew,, ocrd-anybaseocr-dewarp,, ocrd-cis-ocropy-binarize, ocrd-cis-ocropy-denoise, ocrd-cis-ocropy-deskew, ocrd-cis-ocropy-clip, ocrd-kraken-binarize, ocrd-anybaseocr-binarize:
   IL:
     - page
     - region
   OL:
     - page
     - region

 ocrd-cis-ocropy-segment:
   IL:
     - page
     - region
     - line
   OL:
     - region
     - line
     - glyph



 ocrd-im6convert, ocrd-olena-binarize, ocrd-typegroups-classifier:
   IL:
     - page
   OL:
     - page

 ocrd-segment-repair:
   IL:
     - region
   OL:
     - region

 ocrd-cis-ocropy-resegment, ocrd-cis-ocropy-dewarp, ocrd-calamari-recognize, ocrd-cor-asv-ann-evaluate, ocrd-dinglehopper:
   IL:
     - line
   OL:
     - line
 ```

 And as you say, this would enable merging `*-{segment,extract}-*` into single processors
